 
import { useEffect, useMemo, useState } from "react";
import {
  FiActivity,
  FiBarChart2,
  FiCalendar,
  FiClock,
  FiRefreshCw,
  FiTarget,
  FiTrendingDown,
  FiTrendingUp,
} from "react-icons/fi";

import API_BASE from "../../config/api";
 

export default function SignalsPage() {
  const [signals, setSignals] = useState([]);
  const [symbol, setSymbol] = useState("BTCUSDT");
  const [interval, setInterval] = useState("15m");
  const [loading, setLoading] = useState(false);

  const fetchSignals = async () => {
    try {
      setLoading(true);

      const res = await fetch(
        `${API_BASE}/signals-replay?symbol=${symbol}&interval=${interval}`
      );

      const data = await res.json();

      setSignals(data.signals || []);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSignals();
  }, []);

  const formatDate = (time) => {
    const date = new Date(time);
    return date.toLocaleString();
  };

  /* =========================================
     STATISTICS
  ========================================= */

  const stats = useMemo(() => {
    const buy = signals.filter((s) => s.type === "BUY").length;
    const sell = signals.filter((s) => s.type === "SELL").length;

    return {
      total: signals.length,
      buy,
      sell,
    };
  }, [signals]);

  return (
    <div className="signals-page">

      {/* =====================================
          HEADER
      ===================================== */}

      <section className="signals-header">

        <div className="signals-header-left">

          <div className="signals-title-icon">
            <FiActivity />
          </div>

          <div>
            <div className="signals-eyebrow">
              MARKET ANALYTICS
            </div>

            <h1>Signals Replay</h1>

            <p>
              Historical trading signals generated by the strategy engine.
            </p>
          </div>

        </div>

        <div className="signals-live">

          <span className="signals-live-dot"></span>

          <span>ENGINE ACTIVE</span>

        </div>

      </section>


      {/* =====================================
          CONTROL PANEL
      ===================================== */}

      <section className="signals-control-card">

        <div className="control-heading">

          <div className="control-heading-icon">
            <FiBarChart2 />
          </div>

          <div>
            <h2>Replay Configuration</h2>
            <p>
              Select the market and timeframe to analyze.
            </p>
          </div>

        </div>


        <div className="signals-controls">

          <div className="signal-field">

            <label>TRADING PAIR</label>

            <div className="signal-select-wrapper">

              <FiActivity />

              <select
                value={symbol}
                onChange={(e) => setSymbol(e.target.value)}
              >
                <option>BTCUSDT</option>
                <option>ETHUSDT</option>
                <option>SOLUSDT</option>
                <option>BNBUSDT</option>
                <option>XRPUSDT</option>
                <option>SEIUSDT</option>
                <option>NEARUSDT</option>
              </select>

            </div>

          </div>


          <div className="signal-field">

            <label>TIMEFRAME</label>

            <div className="signal-select-wrapper">

              <FiClock />

              <select
                value={interval}
                onChange={(e) => setInterval(e.target.value)}
              >
                <option value="5m">5m</option>
                <option value="15m">15m</option>
                <option value="1h">1h</option>
                <option value="4h">4h</option>
              </select>

            </div>

          </div>


          <button
            className="load-signals-btn"
            onClick={fetchSignals}
            disabled={loading}
          >

            <FiRefreshCw
              className={loading ? "spin" : ""}
            />

            <span>
              {loading ? "Loading..." : "Load Signals"}
            </span>

          </button>

        </div>

      </section>


      {/* =====================================
          STATISTICS
      ===================================== */}

      <section className="signals-stats">

        <div className="signal-stat-card">

          <div className="signal-stat-icon total">
            <FiBarChart2 />
          </div>

          <div>
            <span>Total Signals</span>
            <strong>{stats.total}</strong>
          </div>

        </div>


        <div className="signal-stat-card">

          <div className="signal-stat-icon buy">
            <FiTrendingUp />
          </div>

          <div>
            <span>BUY Signals</span>
            <strong>{stats.buy}</strong>
          </div>

        </div>


        <div className="signal-stat-card">

          <div className="signal-stat-icon sell">
            <FiTrendingDown />
          </div>

          <div>
            <span>SELL Signals</span>
            <strong>{stats.sell}</strong>
          </div>

        </div>


        <div className="signal-stat-card">

          <div className="signal-stat-icon frame">
            <FiTarget />
          </div>

          <div>
            <span>Timeframe</span>
            <strong>{interval}</strong>
          </div>

        </div>

      </section>


      {/* =====================================
          SIGNAL TABLE
      ===================================== */}

      <section className="signals-table-card">

        <div className="table-header">

          <div>

            <div className="table-title-row">

              <FiActivity />

              <h2>Signal History</h2>

            </div>

            <p>
              {symbol} · {interval} · {signals.length} signals detected
            </p>

          </div>


          <div className="table-market-badge">

            <span></span>

            {symbol}

          </div>

        </div>


        {loading ? (

          <div className="signals-loading">

            <div className="loading-spinner"></div>

            <h3>Analyzing Market Data</h3>

            <p>
              The strategy engine is processing historical candles...
            </p>

          </div>

        ) : (

          <>

            {signals.length > 0 ? (

              <div className="signals-table-wrapper">

                <table className="signals-table">

                  <thead>

                    <tr>

                      <th>#</th>

                      <th>Signal</th>

                      <th>Date & Time</th>

                      <th>Price</th>

                      <th>Stop Loss</th>

                      <th>Take Profit</th>

                      <th>Frame</th>

                    </tr>

                  </thead>


                  <tbody>

                    {signals.map((s, i) => (

                      <tr key={i}>

                        <td className="signal-index">
                          {String(i + 1).padStart(2, "0")}
                        </td>


                        <td>

                          <div
                            className={`signal-type ${
                              s.type === "BUY"
                                ? "signal-buy"
                                : "signal-sell"
                            }`}
                          >

                            {s.type === "BUY" ? (
                              <FiTrendingUp />
                            ) : (
                              <FiTrendingDown />
                            )}

                            <span>{s.type}</span>

                          </div>

                        </td>


                        <td>

                          <div className="signal-date">

                            <FiCalendar />

                            <span>
                              {formatDate(s.time)}
                            </span>

                          </div>

                        </td>


                        <td>

                          <span className="price-main">
                            {s.price?.toFixed(2)}
                          </span>

                        </td>


                        <td>

                          <span className="sl-price">
                            {s.stopLoss?.toFixed(2)}
                          </span>

                        </td>


                        <td>

                          <span className="tp-price">
                            {s.takeProfit?.toFixed(2)}
                          </span>

                        </td>


                        <td>

                          <span className="timeframe-badge">
                            {interval}
                          </span>

                        </td>

                      </tr>

                    ))}

                  </tbody>

                </table>

              </div>

            ) : (

              <div className="signals-empty">

                <div className="empty-icon">
                  <FiActivity />
                </div>

                <h3>No Signals Found</h3>

                <p>
                  No trading signals were detected for
                  <strong> {symbol}</strong> on the
                  <strong> {interval}</strong> timeframe.
                </p>

                <button
                  onClick={fetchSignals}
                  className="empty-refresh-btn"
                >
                  <FiRefreshCw />
                  Try Again
                </button>

              </div>

            )}

          </>

        )}

      </section>


      {/* =====================================
          FOOTER INFO
      ===================================== */}

      <div className="signals-footer">

        <div>
          <span className="footer-dot"></span>
          Strategy Engine Online
        </div>

        <span>
          {symbol} / {interval}
        </span>

      </div>

      <style>
        {`
        
/* =========================================================
   SIGNALS PAGE
========================================================= */

.signals-page {
  min-height: 100vh;
  padding: 35px;
  padding-top: 105px;

  background:
    radial-gradient(
      circle at 80% 0%,
      rgba(34, 197, 94, 0.055),
      transparent 30%
    ),
    #070b14;

  color: #f8fafc;

  font-family:
    Inter,
    "Segoe UI",
    Arial,
    sans-serif;

  box-sizing: border-box;
}


/* =========================================================
   HEADER
========================================================= */

.signals-header {
  max-width: 1500px;
  margin: 0 auto 30px;

  display: flex;
  align-items: center;
  justify-content: space-between;

  gap: 25px;
}


.signals-header-left {
  display: flex;
  align-items: center;
  gap: 18px;
}


.signals-title-icon {
  width: 58px;
  height: 58px;

  display: flex;
  align-items: center;
  justify-content: center;

  border-radius: 15px;

  background:
    linear-gradient(
      135deg,
      rgba(34, 197, 94, 0.18),
      rgba(34, 197, 94, 0.05)
    );

  border: 1px solid rgba(34, 197, 94, 0.2);

  color: #22c55e;

  box-shadow:
    0 0 30px rgba(34, 197, 94, 0.08);
}


.signals-title-icon svg {
  width: 28px;
  height: 28px;
}


.signals-eyebrow {
  margin-bottom: 5px;

  color: #22c55e;

  font-size: 11px;
  font-weight: 800;

  letter-spacing: 1.7px;
}


.signals-header h1 {
  margin: 0;

  font-size: 32px;
  line-height: 1.15;

  font-weight: 800;

  letter-spacing: -0.6px;
}


.signals-header p {
  margin: 8px 0 0;

  color: #64748b;

  font-size: 14px;
}


.signals-live {
  display: flex;
  align-items: center;
  gap: 9px;

  padding: 10px 14px;

  border-radius: 30px;

  background: rgba(34, 197, 94, 0.05);

  border: 1px solid rgba(34, 197, 94, 0.13);

  color: #86efac;

  font-size: 10px;
  font-weight: 800;

  letter-spacing: 0.8px;
}


.signals-live-dot {
  width: 8px;
  height: 8px;

  border-radius: 50%;

  background: #22c55e;

  box-shadow:
    0 0 10px rgba(34, 197, 94, 0.8);

  animation: signalPulse 1.7s infinite;
}


@keyframes signalPulse {

  0%,
  100% {
    opacity: 1;
  }

  50% {
    opacity: 0.35;
  }

}


/* =========================================================
   CONTROL CARD
========================================================= */

.signals-control-card {
  max-width: 1500px;
  margin: 0 auto 24px;

  padding: 24px;

  background:
    linear-gradient(
      145deg,
      #0e1726,
      #0b1320
    );

  border: 1px solid #1d2a3d;

  border-radius: 16px;

  box-shadow:
    0 15px 40px rgba(0, 0, 0, 0.16);
}


.control-heading {
  display: flex;
  align-items: center;
  gap: 13px;

  margin-bottom: 22px;
}


.control-heading-icon {
  width: 39px;
  height: 39px;

  display: flex;
  align-items: center;
  justify-content: center;

  border-radius: 10px;

  background: #111e30;

  color: #94a3b8;
}


.control-heading-icon svg {
  width: 19px;
  height: 19px;
}


.control-heading h2 {
  margin: 0;

  font-size: 17px;
  font-weight: 750;
}


.control-heading p {
  margin: 4px 0 0;

  color: #64748b;

  font-size: 12px;
}


/* =========================================================
   CONTROLS
========================================================= */

.signals-controls {
  display: grid;

  grid-template-columns:
    minmax(220px, 1fr)
    minmax(180px, 0.7fr)
    190px;

  gap: 16px;

  align-items: end;
}


.signal-field {
  display: flex;
  flex-direction: column;
  gap: 8px;
}


.signal-field label {
  color: #64748b;

  font-size: 10px;
  font-weight: 800;

  letter-spacing: 1px;
}


.signal-select-wrapper {
  height: 48px;

  display: flex;
  align-items: center;

  gap: 10px;

  padding: 0 14px;

  background: #080f1c;

  border: 1px solid #263449;

  border-radius: 10px;

  transition: 0.2s ease;
}


.signal-select-wrapper:focus-within {
  border-color: rgba(34, 197, 94, 0.55);

  box-shadow:
    0 0 0 3px rgba(34, 197, 94, 0.07);
}


.signal-select-wrapper svg {
  flex-shrink: 0;

  width: 17px;
  height: 17px;

  color: #64748b;
}


.signal-select-wrapper select {
  width: 100%;
  height: 100%;

  border: 0;
  outline: 0;

  background: transparent;

  color: #f8fafc;

  font-size: 14px;
  font-weight: 650;

  cursor: pointer;

  appearance: none;
}


.signal-select-wrapper select option {
  background: #0d1625;
  color: white;
}


.load-signals-btn {
  height: 48px;

  display: flex;
  align-items: center;
  justify-content: center;

  gap: 9px;

  border: 0;
  border-radius: 10px;

  background:
    linear-gradient(
      135deg,
      #22c55e,
      #16a34a
    );

  color: white;

  font-size: 13px;
  font-weight: 750;

  cursor: pointer;

  transition:
    transform 0.2s ease,
    box-shadow 0.2s ease,
    opacity 0.2s ease;
}


.load-signals-btn:hover:not(:disabled) {
  transform: translateY(-2px);

  box-shadow:
    0 10px 25px rgba(34, 197, 94, 0.2);
}


.load-signals-btn:disabled {
  opacity: 0.65;
  cursor: wait;
}


.load-signals-btn svg {
  width: 17px;
  height: 17px;
}


.spin {
  animation: spin 0.9s linear infinite;
}


@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}


/* =========================================================
   STATISTICS
========================================================= */

.signals-stats {
  max-width: 1500px;
  margin: 0 auto 24px;

  display: grid;

  grid-template-columns:
    repeat(4, 1fr);

  gap: 16px;
}


.signal-stat-card {
  min-height: 105px;

  display: flex;
  align-items: center;

  gap: 15px;

  padding: 20px;

  box-sizing: border-box;

  background: #0d1625;

  border: 1px solid #1d2a3d;

  border-radius: 14px;

  transition:
    transform 0.2s ease,
    border-color 0.2s ease;
}


.signal-stat-card:hover {
  transform: translateY(-2px);

  border-color: #2b3c55;
}


.signal-stat-icon {
  width: 46px;
  height: 46px;

  flex-shrink: 0;

  display: flex;
  align-items: center;
  justify-content: center;

  border-radius: 12px;
}


.signal-stat-icon svg {
  width: 21px;
  height: 21px;
}


.signal-stat-icon.total {
  background: rgba(148, 163, 184, 0.08);
  color: #94a3b8;
}


.signal-stat-icon.buy {
  background: rgba(34, 197, 94, 0.09);
  color: #22c55e;
}


.signal-stat-icon.sell {
  background: rgba(239, 68, 68, 0.09);
  color: #ef4444;
}


.signal-stat-icon.frame {
  background: rgba(59, 130, 246, 0.09);
  color: #60a5fa;
}


.signal-stat-card span {
  display: block;

  margin-bottom: 6px;

  color: #64748b;

  font-size: 11px;
  font-weight: 650;
}


.signal-stat-card strong {
  display: block;

  color: #f8fafc;

  font-size: 24px;
  font-weight: 800;
}


/* =========================================================
   TABLE CARD
========================================================= */

.signals-table-card {
  max-width: 1500px;

  margin: 0 auto;

  background: #0d1625;

  border: 1px solid #1d2a3d;

  border-radius: 16px;

  overflow: hidden;

  box-shadow:
    0 15px 40px rgba(0, 0, 0, 0.15);
}


.table-header {
  min-height: 86px;

  padding: 20px 24px;

  display: flex;
  align-items: center;
  justify-content: space-between;

  gap: 20px;

  border-bottom: 1px solid #1d2a3d;
}


.table-title-row {
  display: flex;
  align-items: center;

  gap: 9px;
}


.table-title-row svg {
  color: #22c55e;

  width: 19px;
  height: 19px;
}


.table-title-row h2 {
  margin: 0;

  font-size: 18px;
  font-weight: 750;
}


.table-header p {
  margin: 6px 0 0 28px;

  color: #64748b;

  font-size: 12px;
}


.table-market-badge {
  display: flex;
  align-items: center;
  gap: 8px;

  padding: 9px 13px;

  border-radius: 8px;

  background: #09111e;

  border: 1px solid #223047;

  color: #cbd5e1;

  font-size: 11px;
  font-weight: 750;
}


.table-market-badge span {
  width: 6px;
  height: 6px;

  border-radius: 50%;

  background: #22c55e;

  box-shadow:
    0 0 8px rgba(34, 197, 94, 0.7);
}


/* =========================================================
   TABLE
========================================================= */

.signals-table-wrapper {
  width: 100%;

  overflow-x: auto;
}


.signals-table {
  width: 100%;

  min-width: 850px;

  border-collapse: collapse;

  font-size: 14px;
}


.signals-table th {
  padding: 15px 18px;

  text-align: left;

  background: #0a1220;

  border-bottom: 1px solid #1d2a3d;

  color: #64748b;

  font-size: 10px;
  font-weight: 800;

  text-transform: uppercase;

  letter-spacing: 0.8px;
}


.signals-table td {
  padding: 17px 18px;

  border-bottom: 1px solid rgba(30, 41, 59, 0.65);

  color: #cbd5e1;

  white-space: nowrap;
}


.signals-table tbody tr {
  transition: background 0.18s ease;
}


.signals-table tbody tr:hover {
  background: rgba(255, 255, 255, 0.025);
}


.signals-table tbody tr:last-child td {
  border-bottom: 0;
}


.signal-index {
  color: #475569 !important;

  font-size: 12px;
  font-weight: 700;
}


/* =========================================================
   SIGNAL TYPE
========================================================= */

.signal-type {
  display: inline-flex;
  align-items: center;

  gap: 7px;

  min-width: 78px;

  padding: 7px 10px;

  border-radius: 7px;

  font-size: 11px;
  font-weight: 850;
}


.signal-type svg {
  width: 15px;
  height: 15px;
}


.signal-buy {
  color: #4ade80;

  background: rgba(34, 197, 94, 0.08);

  border: 1px solid rgba(34, 197, 94, 0.12);
}


.signal-sell {
  color: #f87171;

  background: rgba(239, 68, 68, 0.08);

  border: 1px solid rgba(239, 68, 68, 0.12);
}


/* =========================================================
   DATE
========================================================= */

.signal-date {
  display: flex;
  align-items: center;
  gap: 8px;

  color: #94a3b8;
}


.signal-date svg {
  width: 15px;
  height: 15px;

  color: #475569;
}


/* =========================================================
   PRICES
========================================================= */

.price-main {
  color: #f8fafc;

  font-weight: 750;
}


.sl-price {
  color: #f87171;

  font-weight: 650;
}


.tp-price {
  color: #60a5fa;

  font-weight: 650;
}


/* =========================================================
   TIMEFRAME
========================================================= */

.timeframe-badge {
  display: inline-flex;

  align-items: center;
  justify-content: center;

  min-width: 42px;

  padding: 6px 9px;

  border-radius: 6px;

  background: #111e30;

  border: 1px solid #263449;

  color: #94a3b8;

  font-size: 11px;

  font-weight: 750;
}


/* =========================================================
   LOADING
========================================================= */

.signals-loading {
  min-height: 360px;

  display: flex;
  flex-direction: column;

  align-items: center;
  justify-content: center;

  text-align: center;
}


.loading-spinner {
  width: 42px;
  height: 42px;

  margin-bottom: 20px;

  border: 3px solid #1e293b;

  border-top-color: #22c55e;

  border-radius: 50%;

  animation: spin 0.9s linear infinite;
}


.signals-loading h3 {
  margin: 0 0 7px;

  font-size: 17px;
}


.signals-loading p {
  margin: 0;

  color: #64748b;

  font-size: 13px;
}


/* =========================================================
   EMPTY
========================================================= */

.signals-empty {
  min-height: 380px;

  display: flex;
  flex-direction: column;

  align-items: center;
  justify-content: center;

  padding: 40px;

  text-align: center;
}


.empty-icon {
  width: 65px;
  height: 65px;

  display: flex;
  align-items: center;
  justify-content: center;

  margin-bottom: 18px;

  border-radius: 18px;

  background: #111b2b;

  color: #475569;
}


.empty-icon svg {
  width: 28px;
  height: 28px;
}


.signals-empty h3 {
  margin: 0 0 8px;

  font-size: 18px;
}


.signals-empty p {
  max-width: 450px;

  margin: 0;

  color: #64748b;

  font-size: 13px;

  line-height: 1.7;
}


.signals-empty strong {
  color: #cbd5e1;
}


.empty-refresh-btn {
  margin-top: 20px;

  display: flex;
  align-items: center;

  gap: 8px;

  padding: 10px 15px;

  border: 1px solid #263449;

  border-radius: 8px;

  background: #111b2b;

  color: #cbd5e1;

  font-size: 12px;
  font-weight: 700;

  cursor: pointer;

  transition: 0.2s ease;
}


.empty-refresh-btn:hover {
  border-color: #22c55e;
  color: #22c55e;
}


/* =========================================================
   FOOTER
========================================================= */

.signals-footer {
  max-width: 1500px;

  margin: 14px auto 0;

  display: flex;
  justify-content: space-between;

  color: #475569;

  font-size: 10px;
  font-weight: 650;
}


.signals-footer > div {
  display: flex;
  align-items: center;

  gap: 7px;
}


.footer-dot {
  width: 6px;
  height: 6px;

  border-radius: 50%;

  background: #22c55e;
}


/* =========================================================
   LAPTOP
========================================================= */

@media (max-width: 1100px) {

  .signals-page {
    padding: 28px;
    padding-top: 95px;
  }

  .signals-stats {
    grid-template-columns:
      repeat(2, 1fr);
  }

  .signals-controls {
    grid-template-columns:
      1fr 1fr;

  }

  .load-signals-btn {
    grid-column: span 2;
  }

}


/* =========================================================
   TABLET
========================================================= */

@media (max-width: 800px) {

  .signals-page {
    padding: 20px;
    padding-top: 88px;
  }

  .signals-header {
    align-items: flex-start;
  }

  .signals-header h1 {
    font-size: 27px;
  }

  .signals-live {
    display: none;
  }

  .signals-control-card {
    padding: 20px;
  }

  .signals-controls {
    grid-template-columns: 1fr;
  }

  .load-signals-btn {
    grid-column: auto;
  }

  .table-header {
    padding: 18px;
  }

}


/* =========================================================
   MOBILE
========================================================= */

@media (max-width: 600px) {

  .signals-page {
    padding: 15px;
    padding-top: 78px;
  }

  .signals-header {
    margin-bottom: 20px;
  }

  .signals-header-left {
    gap: 12px;
  }

  .signals-title-icon {
    width: 46px;
    height: 46px;

    border-radius: 12px;
  }

  .signals-title-icon svg {
    width: 22px;
    height: 22px;
  }

  .signals-eyebrow {
    font-size: 9px;
  }

  .signals-header h1 {
    font-size: 23px;
  }

  .signals-header p {
    font-size: 11px;
  }


  .signals-control-card {
    padding: 16px;

    border-radius: 13px;
  }

  .control-heading {
    margin-bottom: 17px;
  }

  .control-heading h2 {
    font-size: 15px;
  }

  .control-heading p {
    font-size: 11px;
  }


  .signals-stats {
    gap: 10px;
  }

  .signal-stat-card {
    min-height: 88px;

    padding: 14px;

    gap: 11px;

    border-radius: 11px;
  }

  .signal-stat-icon {
    width: 38px;
    height: 38px;

    border-radius: 9px;
  }

  .signal-stat-icon svg {
    width: 18px;
    height: 18px;
  }

  .signal-stat-card span {
    font-size: 9px;
  }

  .signal-stat-card strong {
    font-size: 19px;
  }


  .signals-table-card {
    border-radius: 13px;
  }

  .table-header {
    min-height: 70px;

    padding: 15px;
  }

  .table-title-row h2 {
    font-size: 15px;
  }

  .table-header p {
    margin-left: 28px;

    font-size: 10px;
  }

  .table-market-badge {
    display: none;
  }


  .signals-table th {
    padding: 12px 14px;
  }

  .signals-table td {
    padding: 14px;
  }


  .signals-footer {
    font-size: 9px;
  }

}


/* =========================================================
   SMALL MOBILE
========================================================= */

@media (max-width: 400px) {

  .signals-stats {
    grid-template-columns: 1fr;
  }

  .signal-stat-card {
    min-height: 75px;
  }

  .signals-header p {
    display: none;
  }

}
 
`}
      </style>

    </div>
  );
}
 
